config/routes.rb
Rails.application.routes.draw do
resources :courses do  
	resources :availabilities
end
  get 'home/schedule'
  get 'home/portfolio'
  root'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
has_many :availabilities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: %i[ show edit update destroy ]
  before_action :set_course

  # GET /availabilities or /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1 or /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities or /availabilities.json
  def create
    @availability = @course.availabilities.create(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to course_url(@course), notice: "Availability was successfully created." }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1 or /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to availability_url(@availability), notice: "Availability was successfully updated." }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1 or /availabilities/1.json
  def destroy
    @availability.destroy

    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: "Availability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def availability_params
      params.require(:availability).permit(:day, :start_time, :end_time, :preferred, :course_id)
    end

    def set_course
        @course=Course.find(params[:course_id])
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

def index
	@courses=Course.all
end

def show
	@course = Course.find(params[:id])
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def schedule
  end
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/availabilities/_availability.html.erb
<div id="<%= dom_id availability %>">
  <p>
    <strong>Day:</strong>
    <%= availability.day %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= availability.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= availability.end_time %>
  </p>

  <p>
    <strong>Preferred:</strong>
    <%= availability.preferred %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= availability.course_id %>
  </p>

</div>

app/views/availabilities/_form.html.erb
<%= form_with(model: availability) do |form| %>
  <% if availability.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
        <% availability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.text_field :day %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.time_field :end_time %>
  </div>

  <div>
    <%= form.label :preferred, style: "display: block" %>
    <%= form.check_box :preferred %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing availability</h1>

<%= render "form", availability: @availability %>

<br>

<div>
  <%= link_to "Show this availability", @availability %> |
  <%= link_to "Back to availabilities", availabilities_path %>
</div>

app/views/availabilities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Availabilities</h1>

<div id="availabilities">
  <% @availabilities.each do |availability| %>
    <%= render availability %>
    <p>
      <%= link_to "Show this availability", availability %>
    </p>
  <% end %>
</div>

<%= link_to "New availability", new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New availability</h1>

<%= form_with model: [ @course, @course.availabilities.build ] do |form| %>
<p>
	<%= form.label :Day %>
	<%= form.text_field :day %>
</p>

<p>
	<%= form.label :start %>
	<%= form.time_field :start_time %>
</p>

<p>
	<%= form.label :End %>
	<%= form.time_field :end_time %>
</p>
<%= form.submit %>
<p>

</p>
<% end %>

app/views/availabilities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @availability %>

<div>
  <%= link_to "Edit this availability", edit_availability_path(@availability) %> |
  <%= link_to "Back to availabilities", availabilities_path %>

  <%= button_to "Destroy this availability", @availability, method: :delete %>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>

<ul>
	<% @courses.each do |course| %>
	<li>
		<%= link_to course.name, course %>
	</li>
	<% end %>
</ul>

app/views/courses/show.html.erb
<h1>
	<%= @course.code %> <br>
	<%= @course.name %>
</h1>


<%= link_to "Add Availability", new_course_availability_path(@course) %>

app/views/home/index.html.erb
<style>
	h1{
		font-family: "Lucida Console", "Courier New", monospace;
		font-size: 60px;
		color: #66FCF1;


	}
	h2{
		font-family: "Lucida Console", "Courier New", monospace;
		color: lightgreen;
	}
	h4{
		font-family: "Lucida Console", "Courier New", monospace;
		color: lightgreen;
	}

  body{
  	background-color: #1F2833;
	}

	p{
		font-family: "Lucida Console", "Courier New", monospace;
		color: lightgreen;
	}

  #backgroundBox{
    border: 10px;
    padding: 15px;
    background: #45A29E;
    background-clip: padding-box;
    width: 50%;
  }

</style>
<body>
<br><br><br>
<center>
  <div id="backgroundBox">
    <h5><p style="color:white;">Welcome to RUSE! If you read out the acronym RUSE, you will see it asks "Are you SE?" This website was made to make the lives of Indiana Tech's software engineering majors easier. On this website, you have the abillity to input your schedule and show off your class projects!</p></h5>
  </div>
</center>
<br>
<center>
<img src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(15%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(30%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(45%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(60%) "src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(75%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(87.5%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
<img style="filter: invert(100%);"src="https://academics.indianatech.edu/wp-content/uploads/sites/25/Brian-Lewandowski-073.jpg"></img>
</center>
<br>
<br>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MylesIsDumb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <style>
  h1{
    font-family: "Lucida Console", "Courier New", monospace;
    font-size: 60px;
    color: #66FCF1;


  }
  h2{
    font-family: "Lucida Console", "Courier New", monospace;
    color: lightgreen;
  }
  h4{
    font-family: "Lucida Console", "Courier New", monospace;
    color: lightgreen;
  }

  body{
    background-color: #1F2833;
  }

  p{
    font-family: "Lucida Console", "Courier New", monospace;
    color: lightgreen;
  }

  #backgroundBox{
    border: 10px;
    padding: 15px;
    background: #45A29E;
    background-clip: padding-box;
    width: 50%;
  }

  a{
    color: #66FCF1;
  }

    <!-- Optional JavaScript; choose one of the two! -->
</style>

<head>
  
<center><h1 class="animate__heartBeat"><span style="color:#45A29E;">RU</span>SE</h1></center>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#66FCF1;">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:3000/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost:3000/home/schedule">Scheduling</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:3000/home/portfolio">Portfolio</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</head>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/></link>
  </head>

  <body>
    <%= yield %>
  </body>
  <div>
<center>
<footer style="color:white">
<a href="http://localhost:3000/">Home</a>
<a href="http://localhost:3000/home/schedule">Scheduling</a>
<a href="http://localhost:3000/home/portfolio">Portfolio</a>
</footer>
</center>
</div>
</html>